name: UI Screenshot Diff

on:
  pull_request:
    branches: [ main ]

jobs:
  screenshot-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Run screenshot tests
        run: |
          npm run test:screenshots
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshot-diff
          path: artifacts/**
